[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "cogwheel-machine"
dynamic = ["version"]

dependencies = [
  "cogwheel-pe",
  "sbi>=0.23.1",
  "xgboost",
]

maintainers = [
  {name = "Javier Roulet", email = "jroulet@caltech.edu"}
]
readme = "README.md"

[project.urls]
"Source" = "https://github.com/jroulet/cogwheel-machine"

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools_scm]
local_scheme = "no-local-version"
version_scheme = "post-release"

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_",
              "ra", "m1", "m2", "q", "dt", "ax"]

ignored-modules = [
  "lal",
]

[tool.pylint.format]
max-line-length = 79
