[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "labrador-gw"
dynamic = ["version"]

dependencies = [
  "cogwheel-pe>=1.6",
  "xgboost",
  "sbi==0.26",
]

maintainers = [
  {name = "Javier Roulet", email = "jroulet@uchicago.edu"}
]
readme = "README.md"

[project.optional-dependencies]
docs = [
  "sphinx",
  "numpydoc",
  "furo",
]

[project.urls]
"Source" = "https://github.com/jroulet/labrador"

[project.scripts]
lab-generate-data-htcondor = "labrador.cli.htcondor:generate_data_cli"
lab-merge-chunks = "labrador.cli.simulation_chunks:merge_chunks_cli"
lab-save-model = "labrador.cli.utils:save_model"
lab-setup-priordir = "labrador.cli.utils:setup_priordir_cli"
lab-setup-rescalerdir = "labrador.cli.utils:setup_rescalerdir_cli"
lab-setup-rundir-and-priordir = "labrador.cli.utils:setup_rundir_and_priordir_cli"
lab-setup-sbidir = "labrador.cli.utils:setup_sbidir_cli"
lab-setup-unfolderdir = "labrador.cli.utils:setup_unfolderdir_cli"
lab-simulate-chunk = "labrador.cli.simulation_chunks:simulate_chunk_cli"

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools_scm]
local_scheme = "no-local-version"
version_scheme = "post-release"

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_",
              "ra", "m1", "m2", "q", "dt", "ax"]

ignored-modules = [
  "lal",
]

[tool.pylint.format]
max-line-length = 79

[tool.pylint.messages_control]
disable = ["logging-fstring-interpolation"]
