universe = vanilla

executable = /home/lucy.thomas/projects/cog/cogwheel-machine/classifier/10k_test/train_classifier.sh
log = /home/lucy.thomas/projects/cog/cogwheel-machine/classifier/10k_test/train_classifier.out
error = /home/lucy.thomas/projects/cog/cogwheel-machine/classifier/10k_test/train_classifier.err
output = /home/lucy.thomas/projects/cog/cogwheel-machine/classifier/10k_test/train_classifier.out

accounting_group = ligo.dev.o4.cbc.waveforms.lalsimulation
accounting_group_user = lucy.thomas

getenv = True

request_CPUs = 1
#request_GPUs = 1
#DeviceName=="NVIDIA A100-SXM4-80GB"
#cuda_version = 12.3
#requirements = CUDARuntimeVersion >= 12.3
request_memory = 16384 MB
request_disk = 1.0 GB

notification = always
queue 1